apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ermp-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ermp-db
    spec:
       containers:
       - name: ermpdb
         image: aker/ermpdb
         ports:
           - containerPort: 3306
         env:
           - name: MYSQL_ROOT_PASSWORD
             value: rootpassword
           - name: MYSQL_USER
             value: mysqluser
           - name: MYSQL_PASSWORD
             value: mysqlpw
---
kind: Service
apiVersion: v1
metadata:
  name: ermp-db
spec:
  selector:
    app: ermp-db
  ports:
    - name: ermp-db
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ermp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ermp
    spec:
       containers:
       - name: commandside
         image: aker/ermp_commandsideservice
         ports:
           - containerPort: 8081
         env:
           - name: SPRING_DATASOURCE_URL
             value: jdbc:mysql://eventuate-service/eventuate
           - name: SPRING_DATASOURCE_USERNAME
             value: mysqluser
           - name: SPRING_DATASOURCE_PASSWORD
             value: mysqlpw
           - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
             value: com.mysql.jdbc.Driver
           - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
             value: eventuate-service:9092
           - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
             value: zookeeper:2181
           - name: EVENTUATELOCAL_CDC_DB_USER_NAME
             value: root
           - name: EVENTUATELOCAL_CDC_DB_PASSWORD
             value: rootpassword
       
       - name: queryside
         image: aker/ermp_querysideservice
         ports:
           - containerPort: 8082
         env:
           - name: SPRING_DATASOURCE_URL
             value: jdbc:mysql://ermp-db/ermp
           - name: SPRING_DATASOURCE_USERNAME
             value: mysqluser
           - name: SPRING_DATASOURCE_PASSWORD
             value: mysqlpw
           - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
             value: com.mysql.jdbc.Driver
           - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
             value: eventuate-service:9092
           - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
             value: zookeeper:2181
           - name: EVENTUATELOCAL_CDC_DB_USER_NAME
             value: root
           - name: EVENTUATELOCAL_CDC_DB_PASSWORD
             value: rootpassword
---
kind: Service
apiVersion: v1
metadata:
  name: ermp
spec:
  type: NodePort
  selector:
    app: ermp
  ports:
    - name: ermp-command
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
    - name: ermp-query
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
