apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ermp-query
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ermp-query
    spec:
       containers:
       - name: ermpdb
         image: aker/ermpdb
         ports:
           - containerPort: 3306
         env:
           - name: MYSQL_ROOT_PASSWORD
             value: rootpassword
           - name: MYSQL_USER
             value: mysqluser
           - name: MYSQL_PASSWORD
             value: mysqlpw
       - name: queryside
         image: aker/ermp_querysideservice
         ports:
           - containerPort: 8080
         env:
           - name: SPRING_DATASOURCE_URL
             value: jdbc:mysql://localhost/ermp
           - name: SPRING_DATASOURCE_USERNAME
             value: mysqluser
           - name: SPRING_DATASOURCE_PASSWORD
             value: mysqlpw
           - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
             value: com.mysql.jdbc.Driver
           - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
             value: eventuate-service:9092
           - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
             value: eventuate-service:2181
           - name: EVENTUATELOCAL_CDC_DB_USER_NAME
             value: root
           - name: EVENTUATELOCAL_CDC_DB_PASSWORD
             value: rootpassword
---
kind: Service
apiVersion: v1
metadata:
  name: ermp-queryservice
spec:
  type: NodePort
  selector:
    app: ermp-query
  ports:
    - name: ermp-query
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30082
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ermp-command
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ermp-command
    spec:
       containers:
       - name: commandside
         image: aker/ermp_commandsideservice
         ports:
           - containerPort: 8080
         env:
           - name: SPRING_DATASOURCE_URL
             value: jdbc:mysql://eventuate-service/eventuate
           - name: SPRING_DATASOURCE_USERNAME
             value: mysqluser
           - name: SPRING_DATASOURCE_PASSWORD
             value: mysqlpw
           - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
             value: com.mysql.jdbc.Driver
           - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
             value: eventuate-service:9092
           - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
             value: eventuate-service:2181
           - name: EVENTUATELOCAL_CDC_DB_USER_NAME
             value: root
           - name: EVENTUATELOCAL_CDC_DB_PASSWORD
             value: rootpassword
---
kind: Service
apiVersion: v1
metadata:
  name: ermp-commandservice
spec:
  type: NodePort
  selector:
    app: ermp-command
  ports:
    - name: ermp-command
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081

